AWSTemplateFormatVersion: '2010-09-09'
Description:
  Create Budgets
# ------------------------------------------------------------#
#  Metadata
# ------------------------------------------------------------#
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: "AWS Budget Configuration"
        Parameters:
          - BudgetName
          - Ammount
          - ThreshouldHigh
          - ThreshouldMid
          - ThreshouldLow

# ------------------------------------------------------------#
#  InputParameters
# ------------------------------------------------------------#
Parameters:
  BudgetName:
    Type: String
    Default: CloudDivision-Budget
    Description: Budget Name
  Ammount:
    Type: String
    Default: 300
    Description: Budget Limit Amount
  ThreshouldHigh:
    Type: Number
    Default: 100
    MinValue: 50
    MaxValue: 100
    Description: 50-100 % of budgeted AmountHigh
  ThreshouldMid:
    Type: Number
    Default: 80
    MinValue: 50
    MaxValue: 100
    Description: 50-100 % of budgeted AmountMiddle
  ThreshouldLow:
    Type: Number
    Default: 50
    MinValue: 5
    MaxValue: 100
    Description: 50-100 % of budgeted AmountLow

# ------------------------------------------------------------#
#  Resources
# ------------------------------------------------------------#
Resources:
# ------------------------------------------------------------#
#  BudgetAlarts
# ------------------------------------------------------------#    
  BudgetAlarts:
    Type: "AWS::Budgets::Budget"
    Properties:
      Budget:
        BudgetName: !Ref BudgetName
        BudgetLimit:
          Amount: !Ref Ammount
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: !Ref ThreshouldHigh
          Subscribers:
            - SubscriptionType: SNS
              Address: !ImportValue cfn-sns-topic-inamura-arn
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: !Ref ThreshouldMid
          Subscribers:
          - SubscriptionType: SNS
            Address: !ImportValue cfn-sns-topic-inamura-arn
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            Threshold: !Ref ThreshouldLow
          Subscribers:
          - SubscriptionType: SNS
            Address: !ImportValue cfn-sns-topic-inamura-arn